/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ifan
 */
public class Frame1 extends javax.swing.JFrame {
    String jns = "";
    int jml;

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        getJumlah();
        setJenis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bil1 = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        b4 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        bil4 = new javax.swing.JLabel();
        jmlBil = new javax.swing.JComboBox<>();
        btnHitung = new javax.swing.JButton();
        thasil = new javax.swing.JTextField();
        ket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PROGRAM ARITMATIKA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 240, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 110, 30);

        jenis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian", "sisa hasil bagi" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(230, 60, 190, 30);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi"));
        panel.setLayout(null);

        jLabel3.setText("Jumlah Bilangan");
        panel.add(jLabel3);
        jLabel3.setBounds(30, 60, 100, 30);

        bil1.setText("Bilangan 1");
        panel.add(bil1);
        bil1.setBounds(30, 100, 110, 30);

        bil2.setText("Bilangan 2");
        panel.add(bil2);
        bil2.setBounds(30, 140, 110, 30);

        bil3.setText("Bilangan 3");
        panel.add(bil3);
        bil3.setBounds(30, 180, 110, 30);
        panel.add(b4);
        b4.setBounds(140, 220, 220, 30);
        panel.add(b1);
        b1.setBounds(140, 100, 220, 30);
        panel.add(b2);
        b2.setBounds(140, 140, 220, 30);
        panel.add(b3);
        b3.setBounds(140, 180, 220, 30);

        bil4.setText("Bilangan 4");
        panel.add(bil4);
        bil4.setBounds(30, 220, 110, 30);

        jmlBil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        jmlBil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlBilActionPerformed(evt);
            }
        });
        panel.add(jmlBil);
        jmlBil.setBounds(140, 60, 220, 30);

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        panel.add(btnHitung);
        btnHitung.setBounds(200, 260, 63, 23);
        panel.add(thasil);
        thasil.setBounds(140, 300, 220, 100);
        panel.add(ket);
        ket.setBounds(50, 20, 290, 30);

        getContentPane().add(panel);
        panel.setBounds(30, 110, 390, 420);

        setBounds(0, 0, 469, 591);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
         Double hsl = 0.0;
        Double a1, a2, a3, a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());

        if(jns.equals("penjumlahan")) {
            if(jml == 2) {
                hsl = a1 + a2;
                thasil.setText(""+a1 + " + " + a2 + " = " + hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 + a2 + a3;
                thasil.setText(""+a1 + " + " + a2 + " + " + a3 + " = " + hsl);
            }
            if(jml == 4) {
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                thasil.setText(""+a1 + " + " + a2 + " + " + a3 + " + " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("pengurangan")) {
            if(jml == 2) {
                hsl = a1 - a2;
                thasil.setText(""+a1 + " - " + a2 + " = " + hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 - a2 - a3;
                thasil.setText(""+a1 + " - " + a2 + " - " + a3 + " = " + hsl);
            }
            if(jml == 4) {
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 - a2 - a3 - a4;
                thasil.setText(""+a1 + " - " + a2 + " - " + a3 + " - " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("perkalian"))  {
            if(jml == 2) {
                hsl = a1 * a2;
                thasil.setText(""+a1 + " x " + a2 + " = " + hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 * a2 * a3;
                thasil.setText(""+a1 + " x " + a2 + " x " + a3 + " = " + hsl);
            }
            if(jml == 4) {
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                thasil.setText(""+a1 + " x " + a2 + " x " + a3 + " x " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("pembagian"))  {
            if(jml == 2) {
                hsl = a1 / a2;
                thasil.setText(""+a1 + " : " + a2 + " = " + hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 / a2 / a3;
                thasil.setText(""+a1 + " : " + a2 + " : " + a3 + " = " + hsl);
            }
            if(jml == 4) {
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                thasil.setText(""+a1 + " : " + a2 + " : " + a3 + " : " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("sisa hasil bagi"))  {
            hsl = a1 % a2;
            thasil.setText(""+a1 + " : " + a2 + " = " + (a1 - hsl)/a2 + " sisa " + hsl);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnHitungActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void jmlBilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlBilActionPerformed
        getJumlah();
    }//GEN-LAST:event_jmlBilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JButton btnHitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JComboBox<String> jmlBil;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField thasil;
    // End of variables declaration//GEN-END:variables

    private void getJumlah() {
        if(jmlBil.getSelectedItem().equals("2")){
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            jml = 2;
        } else if(jmlBil.getSelectedItem().equals("3")){
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            jml = 3;
        } else if(jmlBil.getSelectedItem().equals("4")){
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            jml = 4;
        }
    } //To change body of generated methods, choose Tools | Templates.

    private void setJenis() {
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns = "Penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            jmlBil.setEnabled(true);
        } 
        else if(jenis.getSelectedItem().equals("Pengurangan")) {
            jns = "Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            jmlBil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Perkalian")){ 
            jns = "Perkalian"; 
            ket.setText("Perkalian");
            panel.setVisible(true);
            jmlBil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pembagian")){
            jns = "Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            jmlBil.setEnabled(true);
        } 
        else if(jenis.getSelectedItem().equals("sisa hasil bagi")){
            jns = "sisa hasil bagi";
            ket.setText("sisa hasil bagi");
            panel.setVisible(true);
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            jml = 2;
            jmlBil.setEnabled(false);
}
        else {
            jns = null;
            panel.setVisible(false);
        } //To change body of generated methods, choose Tools | Templates.
    }
}